"""Schemas for metadata events generated by core platform workflows."""

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel, ConfigDict


class MetadataEventRead(BaseModel):
    """Structured metadata event exposed to API consumers."""

    id: int
    workspace_id: int
    event_type: str
    resource_type: str | None
    resource_id: int | None
    actor: str | None
    details: dict[str, Any]
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)
